#+title: N-Version Programming
#+author: conao3

[[https://github.com/conao3/n-version-programming/blob/master/LICENSE][https://img.shields.io/github/license/conao3/n-version-programming.svg?style=flat-square]]
[[https://github.com/conao3/n-version-programming/releases][https://img.shields.io/github/tag/conao3/n-version-programming.svg?style=flat-square]]

* Overview

A practical demonstration of N-version programming, a software fault tolerance technique where multiple independent implementations of the same specification run in parallel. Results are compared using majority voting to detect and mask errors.

This project implements quicksort across multiple languages and compilers to illustrate how diverse implementations can provide reliable outputs even when individual versions contain bugs.

* Features

- Multiple quicksort implementations across different languages:
  - C (gcc, clang)
  - C++ (g++, clang++)
  - Emacs Lisp (interpreted and byte-compiled)
  - Common Lisp (CLISP, SBCL)
- Automatic execution of all implementations
- Majority voting system for result determination
- Docker-based environment for consistent execution

* Requirements

- [[https://docs.docker.com/][Docker]]
- [[https://docs.docker.com/compose/][Docker Compose]]

* Usage

Run all implementations and perform majority voting:

#+begin_src shell
make
#+end_src

This command will:
1. Start the Docker container
2. Execute all quicksort implementations with the same input
3. Compare results and apply majority voting
4. Display the consensus result

** Example Output

#+begin_src text
=== Results ===
      2 0 6 10 10 25 42 47 54 56 77 110 121 146 147 220 247
     29 6 10 10 25 42 47 54 56 77 110 121 146 147 220 247 376

=== Majority vote ===
 6 10 10 25 42 47 54 56 77 110 121 146 147 220 247 376
#+end_src

In this example, 29 implementations produced the correct sorted output, while 2 implementations (intentionally buggy) produced incorrect results. The majority voting system correctly identifies and outputs the correct result.

* How It Works

N-version programming operates on the principle that independently developed implementations are unlikely to fail in the same way. By running multiple versions and comparing their outputs, the system can:

1. Detect errors when outputs disagree
2. Determine the correct output through majority voting
3. Continue operating correctly even when some implementations fail

This project includes intentionally buggy implementations (e.g., =qsort-vector-bug.cpp=) to demonstrate the fault tolerance mechanism.

* License

MIT License

Copyright (c) Naoya Yamashita

See [[https://github.com/conao3/n-version-programming/blob/master/LICENSE][LICENSE]] for details.

* Author

Naoya Yamashita ([[https://github.com/conao3][conao3]])
