#!/bin/sh

cd "$(dirname "$0")"
if [ ! -f .random ]; then
  echo ".random file missing!  Please create .random file."
  exit 1
fi

set -x

rm -rf .result

## interpreters
cat .random | emacs --script qsort.el >> .result
cat .random | emacs --script qsort-sort.el >> .result
cat .random | emacs --script qsort-sort-threading-macro.el >> .result
cat .random | emacs --script qsort-one-function.el >> .result
cat .random | clisp qsort.lisp >> .result
cat .random | sbcl --script qsort.lisp >> .result

## compilers
emacs --batch -f batch-byte-compile qsort.el && cat .random | emacs --script qsort.elc >> .result
emacs --batch -f batch-byte-compile qsort-sort.el && cat .random | emacs --script qsort-sort.elc >> .result
emacs --batch -f batch-byte-compile qsort-sort-threading-macro.el && cat .random | emacs --script qsort-sort-threading-macro.elc >> .result
emacs --batch -f batch-byte-compile qsort-one-function.el && cat .random | emacs --script qsort-one-function.elc >> .result
clisp -c qsort.lisp && cat .random | clisp qsort >> .result
gcc qsort.c && cat .random | ./a.out >> .result
gcc qsort-one-function.c && cat .random | ./a.out >> .result
gcc qsort-one-function-med3.c && cat .random | ./a.out >> .result
gcc qsort-one-function-med3-tri.c && cat .random | ./a.out >> .result
gcc qsort-one-function-pointer.c && cat .random | ./a.out >> .result
gcc qsort-one-function-pointer-med3.c && cat .random | ./a.out >> .result
clang qsort.c && cat .random | ./a.out >> .result
clang qsort-one-function.c && cat .random | ./a.out >> .result
clang qsort-one-function-med3.c && cat .random | ./a.out >> .result
clang qsort-one-function-med3-tri.c && cat .random | ./a.out >> .result
clang qsort-one-function-pointer.c && cat .random | ./a.out >> .result
clang qsort-one-function-pointer-med3.c && cat .random | ./a.out >> .result
g++ qsort.cpp && cat .random | ./a.out >> .result
g++ qsort-vector.cpp && cat .random | ./a.out >> .result
g++ qsort-vector-bug.cpp && cat .random | ./a.out >> .result
g++ qsort-vector-sort.cpp && cat .random | ./a.out >> .result
clang++ qsort.cpp && cat .random | ./a.out >> .result
clang++ qsort-vector.cpp && cat .random | ./a.out >> .result
clang++ qsort-vector-bug.cpp && cat .random | ./a.out >> .result
clang++ qsort-vector-sort.cpp && cat .random | ./a.out >> .result

set +x
echo
echo '=== Process complete ==='

cat .result | sort | uniq -c
